### ISSUE TITLE
Issue with downloading the package

### ISSUE THREAD

**Issue by jcjunder** [AlexandreWadoux/soilspec#5]
Hello, 

I've tried to download this package multiple times, and always run into the same errors. 

Here are all the steps I've taken to troubleshoot it: 

Standard Installation via GitHub:

Used devtools::install_github("AlexandreWadoux/soilspec"), which consistently resulted in a "lazy loading failed for package 'soilspec'" error during the installation process.
Manual Installation from a .tar.gz File:

Attempted to manually download the soilspec package and install it using:
R
Copy code
devtools::install_local("C:/Users/jcjun/OneDrive/Documents/R/win-library/soilspec/soilspec_0.1.0.tar.gz")
This also resulted in the same "lazy loading failed" error.
Checked for Dependencies:

Verified the package dependencies listed in the DESCRIPTION file and tried manually installing them using:
R
Copy code
install.packages(c("stats", "utils", "methods", "base", "graphics", "grDevices", "cluster", "MASS", "scales", "reshape2", "ggplot2", "gridExtra", "data.table"))
Increased Verbosity and Examined Traceback:

Used options(error = traceback) and options(error = function() traceback(3)) to get more detailed error information when the installation failed, but no clear specific error message pinpointing the issue was found.
Disabled Lazy Loading:

Attempted to disable lazy loading during the installation process by setting:
R
Copy code
Sys.setenv(R_INSTALL_STAGED = FALSE)
devtools::install_local("C:/Users/jcjun/OneDrive/Documents/R/win-library/soilspec/soilspec_0.1.0.tar.gz")
The same error occurred, with no improvement.
Checked for Locked Files and Conflicts:

Manually checked for and deleted any previous soilspec installation files or 00LOCK folders in the R library to ensure no remnants from failed installations were causing conflicts.
Tried reinstalling after cleaning up the library path, but the issue persisted.
Ran R as Administrator:

Tried running R and RStudio as an administrator to avoid potential permission issues during installation. This did not resolve the error.
Tried on Multiple Versions of R:

Verified that the issue persisted across multiple R versions, ensuring that it wasn't related to a specific version incompatibility.

....

I am still getting the following error messages: 
"lazy loading failed for package 'soilspec'"
"installation of package had non-zero exit status"

I don't know if there is a bug in the system, or if it might be due to it being built in a different version of R. 

Any help would be appreciated. 

Thank you.

**Comment by AlexandreWadoux** [comment]
Hello, I have tried to install it on another laptop and it worked. Make sure you have Rtools installed https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html

**Comment by jcjunder** [comment]
Hello, I've updated all my Rstudio, and Rtools, and R to be the latest versions. But I'm still getting the same error message though as before, I've shared it below. I've not used R for very complicated stuff before, so this is a bit beyond me. Do you have any ideas of what I could try next? I'd really like to be able to use this package. 

I have a slightly strange laptop - windows, but with an ARM processor - its caused me problems before with apps not working, but i haven't had issues with R before - could this be causing the issue? I downloaded the Rtools 44 made for ARM processors. 

Thank you for your help, fingers crossed I get to use your package, 

Jessica


> library(devtools)
> 
> devtools::install_github("AlexandreWadoux/soilspec", force = FALSE)
Downloading GitHub repo AlexandreWadoux/soilspec@HEAD
── R CMD build ─────────────────────────────────
✔  checking for file 'C:\Users\jcjun\AppData\Local\Temp\RtmpYffa4O\remotescfc4a3876af\AlexandreWadoux-soilspec-cfd1758/DESCRIPTION' (773ms)
─  preparing 'soilspec': (545ms)
✔  checking DESCRIPTION meta-information (521ms)
─  checking for LF line-endings in source and make files and shell scripts (521ms)
─  checking for empty or unneeded directories (459ms)
─  building 'soilspec_0.1.0.tar.gz' (457ms)
   
Installing package into ‘C:/Users/jcjun/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'soilspec' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package 'soilspec'
* removing 'C:/Users/jcjun/AppData/Local/R/win-library/4.3/soilspec'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/jcjun/AppData/Local/Temp/RtmpYffa4O/filecfc56962af/soilspec_0.1.0.tar.gz’ had non-zero exit status
